// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wicaxumfwnofvypygdbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpY2F4dW1md25vZnZ5cHlnZGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODI5MjIsImV4cCI6MjA3NDU1ODkyMn0.eQH6NiXBMkQ4ZevB8ruhpA_JOVxnOw3qSkdP1aAY7LE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});